oro_frontend:
    resource:     "@OroFrontendBundle/Controller/FrontendController.php"
    type:         annotation
    options:
        frontend: true

oro_frontend_datagrid:
    resource:     "@OroFrontendBundle/Controller/GridController.php"
    type:         annotation
    options:
        frontend: true

oro_frontend_api:
    resource: "@OroFrontendBundle/Resources/config/oro/routing_api.yml"

oro_frontend_dictionary_search:
    path: /dictionary/{dictionary}/search
    defaults: { _controller: OroEntityBundle:Dictionary:search }
    options:
        frontend: true

oro_frontend_dictionary_value:
    path: /dictionary/{dictionary}/values
    defaults: { _controller: OroEntityBundle:Dictionary:values }
    options:
        frontend: true

oro_frontend_datagrid_index:
    path: /datagrid/{gridName}
    defaults: { _controller: OroDataGridBundle:Grid:get }
    requirements:
        gridName: '[\w\:-]+'
    options:
        frontend: true

oro_frontend_action:
    resource: "@OroFrontendBundle/Resources/config/oro/routing_action.yml"

oro_frontend_workflow:
    resource: "@OroFrontendBundle/Resources/config/oro/routing_workflow.yml"

oro_frontend_js_routing_js:
    path: "/media/js/frontend_routes.{_format}"
    defaults: { _controller: oro_frontend.js_routing_controller:indexAction }
    requirements:
        _format: json
    options:
        frontend: true

oro_datagrid_front_mass_action:
    path: '{gridName}/massFrontAction/{actionName}'
    defaults:
        _controller: OroDataGridBundle:Grid:massAction
    requirements:
        gridName:   '[\w\:\-]+'
        actionName: '[\w\-]+'
    options:
        frontend: true
